name: "python-tokenizer"
backend: "python"
max_batch_size: 0


input [
    {
        name: "TEXTS_SOURCE"
        data_type: TYPE_STRING
        dims: [ -1 ]
    },
    {
        name: "TEXTS_TARGET"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]

output [
    {
        name: "source"
        data_type: TYPE_INT32
        dims: [ -1, 50 ]
    },
    {
        name: "target"
        data_type: TYPE_INT32
        dims: [ -1, 50 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
